"""Shadow homeowner promotion for qualified external topology evidence.

This adapter extends the commissioned observation-only HA observer. It may promote qualified
context-less external leaf or exact-group evidence into shadow homeowner intent, but it never
calls Home Assistant services or commands a light.
"""

from __future__ import annotations

from collections import deque
from collections.abc import Callable
from copy import deepcopy
from dataclasses import dataclass
from datetime import datetime, timedelta

from homeassistant.core import Event, HomeAssistant, State, callback
from homeassistant.helpers.event import async_call_later
from homeassistant.util import dt as dt_util

from .attribution_correlation import (
    ExternalBurstTopology,
    resolve_unique_exact_group,
)
from .ha_observer import (
    EXTERNAL_BURST_WINDOW_SECONDS,
    HomeAssistantShadowObserver,
    _appearance_from_state,
)
from .intent_policy import (
    IntentAttributionSource,
    IntentDisposition,
    IntentEvidence,
    IntentEvidenceKind,
)
from .model import Appearance, LayerKind
from .operations import HomeownerOperation, MemberOutcome, OperationResult
from .shadow import ShadowDecision, ShadowObservation

_SURFACE_GUARDS: tuple[tuple[str, str], ...] = (
    ("light.holiday_main_area", "input_boolean.home_lighting_ha_guard_main_area"),
    ("light.front_eve_zone", "input_boolean.home_lighting_ha_guard_front_eve"),
    ("light.holiday_path", "input_boolean.home_lighting_ha_guard_path"),
    ("light.holiday_backyard", "input_boolean.home_lighting_ha_guard_backyard"),
)

# Home Hue Scene Monitor exposes one authoritative timestamp sensor per commissioned
# Hue surface. A strictly newer recall with the manager guard inactive is stronger
# homeowner evidence than the context-less leaf churn generated by the bridge.
_SCENE_RECALL_SOURCES: dict[str, tuple[str, str, str | None]] = {
    "sensor.main_area_last_recall": (
        "light.holiday_main_area",
        "input_boolean.home_lighting_ha_guard_main_area",
        "binary_sensor.hue_bridge_living_room",
    ),
    "sensor.front_eve_last_recall": (
        "light.front_eve_zone",
        "input_boolean.home_lighting_ha_guard_front_eve",
        None,
    ),
    "sensor.path_last_recall": (
        "light.holiday_path",
        "input_boolean.home_lighting_ha_guard_path",
        None,
    ),
    "sensor.backyard_last_recall": (
        "light.holiday_backyard",
        "input_boolean.home_lighting_ha_guard_backyard",
        "binary_sensor.hue_bridge_backyard",
    ),
}

# Front Eve is one physical Festavia leaf behind a one-member Hue aggregate. The
# aggregate repeats the same bridge telemetry and therefore cannot independently
# corroborate a context-less leaf command. Direct HA user context and genuine raw
# Hue scene recall remain separate high-confidence homeowner evidence paths.
_CONTEXTLESS_SINGLE_MEMBER_SURFACES = frozenset({"light.front_eve_zone"})

# Hue can fan a large scene across the Backyard for several seconds while leaving
# status.last_recall unchanged. Keep this separate from the ordinary 2-second
# external-command burst so broad ambiguity does not become easier to promote.
SCENE_DISPLACEMENT_CORROBORATION_SECONDS = 8.0
SURFACE_GROUP_OFF_CORRELATION_SECONDS = 8.0


@dataclass(frozen=True)
class _PendingExternalLeaf:
    """Original context-less leaf observation retained for one short correlation window."""

    observed_at: datetime
    observation: ShadowObservation
    state: State


class PromotingHomeAssistantShadowObserver(HomeAssistantShadowObserver):
    """Promote only qualified external leaf or exact-group correlation into shadow ownership."""

    def __init__(
        self,
        hass: HomeAssistant,
        entity_ids: list[str],
        manual_precedence: dict[str, int] | None = None,
        surface_exclusions: dict[str, list[str]] | None = None,
    ) -> None:
        super().__init__(hass, entity_ids, manual_precedence, surface_exclusions)
        self._armed_off_attempts: deque[dict] = deque(maxlen=32)
        self._off_leaf_evidence: deque[dict] = deque(maxlen=64)
        self._pending_external_leaves: dict[str, _PendingExternalLeaf] = {}
        self._pending_single_promotions: dict[
            tuple[int | None, str], Callable[[], None]
        ] = {}
        self._pending_overlapping_group_promotions: dict[
            tuple[str, str, tuple[tuple[str, int], ...]],
            tuple[frozenset[str], Callable[[], None]],
        ] = {}
        self._last_external_promotion_key: tuple[int | None, str] | None = None
        self._last_external_promotion_outcome: dict[str, object] | None = None
        self._last_external_group_promotion_key: tuple[
            str, str, tuple[tuple[str, int], ...]
        ] | None = None
        self._last_external_group_promotion_outcome: dict[str, object] | None = None
        self._external_group_burst_topology: dict[str, tuple[str, ...]] = {}
        self._external_group_last_observed_at: datetime | None = None
        self._scene_recall_settle_until: dict[str, datetime] = {}
        self._scene_displacement_until: dict[str, datetime] = {}
        self._scene_displacement_evidence: dict[str, dict[str, object]] = {}
        self._recent_surface_appearance_evidence: dict[str, dict[str, object]] = {}

    async def _async_state_changed(self, event: Event) -> None:
        """Consume authoritative Hue scene recalls before ordinary light telemetry."""
        entity_id = event.data.get("entity_id")
        source = _SCENE_RECALL_SOURCES.get(entity_id)
        if source is None:
            await super()._async_state_changed(event)
            return
        await self._async_scene_recall_changed(event, *source)

    async def _async_scene_recall_changed(
        self,
        event: Event,
        aggregate_id: str,
        guard_id: str,
        sync_entity_id: str | None,
    ) -> None:
        """Promote one newer raw Hue scene recall as an exact homeowner group operation."""
        old_state = event.data.get("old_state")
        new_state = event.data.get("new_state")
        if not isinstance(old_state, State) or not isinstance(new_state, State):
            return

        old_ts = dt_util.parse_datetime(old_state.state)
        new_ts = dt_util.parse_datetime(new_state.state)

        guard = self.hass.states.get(guard_id)
        if guard is None or guard.state != "off":
            return
        if sync_entity_id is not None:
            sync = self.hass.states.get(sync_entity_id)
            if sync is None or sync.state != "off":
                return

        if old_ts is None or new_ts is None:
            return
        if new_ts <= old_ts:
            old_active = old_state.attributes.get("active")
            new_active = new_state.attributes.get("active")
            if (
                new_ts == old_ts
                and isinstance(old_active, str)
                and old_active not in ("", "inactive")
                and new_active == "inactive"
            ):
                # Hue occasionally displaces a running scene without advancing
                # status.last_recall (observed on the Backyard room/zone). This
                # attribute transition is not sufficient homeowner evidence by
                # itself; it only opens a short corroboration window for a coherent
                # external surface-wide appearance burst.
                self._scene_displacement_until[aggregate_id] = dt_util.now() + timedelta(
                    seconds=SCENE_DISPLACEMENT_CORROBORATION_SECONDS
                )
                recent = self._recent_surface_appearance_evidence.get(aggregate_id, {})
                recent_at = recent.get("updated_at")
                recent_leaves = recent.get("leaf_entities")
                leaf_entities = set()
                aggregate_seen = False
                if (
                    isinstance(recent_at, datetime)
                    and (dt_util.now() - recent_at).total_seconds()
                    <= SCENE_DISPLACEMENT_CORROBORATION_SECONDS
                ):
                    if isinstance(recent_leaves, set):
                        leaf_entities = set(recent_leaves)
                    aggregate_seen = recent.get("aggregate_seen") is True
                self._scene_displacement_evidence[aggregate_id] = {
                    "leaf_entities": leaf_entities,
                    "aggregate_seen": aggregate_seen,
                }
            return

        self._scene_displacement_until.pop(aggregate_id, None)
        self._scene_displacement_evidence.pop(aggregate_id, None)

        scene_id = new_state.attributes.get("scene_id")
        if not isinstance(scene_id, str) or not scene_id or len(scene_id) > 256:
            return

        self._refresh_topology_cache()
        members = tuple(
            entity_id
            for entity_id in self._topology_members.get(aggregate_id, ())
            if entity_id in self.entity_ids
        )
        if not members:
            return

        # A recall is the authoritative receipt for this surface. Discard provisional
        # leaf inference and suppress the bridge's immediate scene-rendering churn.
        for member in members:
            self._pending_external_leaves.pop(member, None)
        self._cancel_pending_single_for_entities(members)
        self._cancel_pending_group_promotions_for_entities(members)
        self._external_correlator.reset()
        self._external_burst = None
        self._external_group_burst_topology = {}
        self._external_group_last_observed_at = None
        self._scene_recall_settle_until[aggregate_id] = dt_util.now() + timedelta(
            seconds=EXTERNAL_BURST_WINDOW_SECONDS
        )

        for member in members:
            self._post_boundary_off_entities.discard(member)

        sequence = self.runtime.reserve_sequence()
        evidence = IntentEvidence(
            kind=IntentEvidenceKind.CORRELATED_EXTERNAL_HOMEOWNER_COMMAND,
            attribution_coherent=True,
            attribution_source=IntentAttributionSource.UNATTRIBUTED_EXTERNAL,
            has_user_id=False,
            has_parent_id=False,
        )
        scene_name = new_state.attributes.get("scene_name")
        scene_evidence = (
            f"{event.data.get('entity_id')}:{new_state.state}:"
            f"{scene_name if isinstance(scene_name, str) else ''}"
        )
        result = self.runtime.observe_operation(
            HomeownerOperation(
                operation_id=f"hue-scene:{event.data.get('entity_id')}:{new_state.state}",
                sequence=sequence,
                generation=self.runtime.engine.generation,
                kind="appearance",
                evidence=evidence,
                members=tuple(
                    MemberOutcome(
                        member,
                        appearance=Appearance(
                            on=True,
                            scene_id=scene_id,
                            scene_evidence=scene_evidence,
                        ),
                        manual_precedence=self.manual_precedence.get(member),
                    )
                    for member in members
                ),
                group_id=aggregate_id,
            )
        )
        self._last_decision = ShadowDecision(
            aggregate_id,
            result.intent,
            result.mutated,
            result.reason,
        )
        self._evidence_ledger.append(
            {
                "timestamp": dt_util.now().isoformat(),
                "entity_id": event.data.get("entity_id"),
                "operation": "scene_recall",
                "evidence_kind": evidence.kind.value,
                "attribution_source": evidence.attribution_source.value,
                "user_context": False,
                "parent_context": False,
                "entity_role": "authoritative_scene_recall",
                "member_count": len(members),
                "intent": result.intent.disposition.value,
                "allows_homeowner_mutation": result.intent.allows_homeowner_mutation,
                "mutated": result.mutated,
                "reason": result.reason,
            }
        )
        if result.mutated:
            await self.async_save()
        else:
            self._publish_diagnostics()

    @callback
    def _managed_membership_changed(
        self, added: tuple[str, ...], removed: tuple[str, ...]
    ) -> None:
        """Invalidate provisional correlation whenever canonical membership changes."""
        affected = tuple(sorted(set(added) | set(removed)))
        for entity_id in affected:
            self._pending_external_leaves.pop(entity_id, None)
        self._cancel_pending_single_for_entities(affected)
        self._cancel_pending_group_promotions_for_entities(affected)
        self._external_correlator.reset()
        self._external_burst = None
        self._external_group_burst_topology = {}
        self._external_group_last_observed_at = None
        for group_id in tuple(self._scene_displacement_until):
            members = set(self._topology_members.get(group_id, ()))
            if members & set(affected):
                self._scene_displacement_until.pop(group_id, None)
                self._scene_displacement_evidence.pop(group_id, None)
                self._recent_surface_appearance_evidence.pop(group_id, None)

    async def async_reset_homeowner_control(self) -> dict[str, int]:
        """Cancel pre-reset promotion evidence, then clear homeowner ownership state."""
        for cancel in tuple(self._pending_single_promotions.values()):
            cancel()
        self._pending_single_promotions.clear()
        for _members, cancel in tuple(self._pending_overlapping_group_promotions.values()):
            cancel()
        self._pending_overlapping_group_promotions.clear()
        self._pending_external_leaves.clear()
        self._external_group_burst_topology = {}
        self._external_group_last_observed_at = None
        self._scene_recall_settle_until.clear()
        self._scene_displacement_until.clear()
        self._scene_displacement_evidence.clear()
        self._recent_surface_appearance_evidence.clear()
        self._last_external_promotion_key = None
        self._last_external_promotion_outcome = None
        self._last_external_group_promotion_key = None
        self._last_external_group_promotion_outcome = None
        return await super().async_reset_homeowner_control()

    async def async_shutdown(self) -> None:
        """Cancel provisional promotions before unregistering the observer."""
        for cancel in tuple(self._pending_single_promotions.values()):
            cancel()
        self._pending_single_promotions.clear()
        for _members, cancel in tuple(self._pending_overlapping_group_promotions.values()):
            cancel()
        self._pending_overlapping_group_promotions.clear()
        await super().async_shutdown()

    @callback
    def _handle_nightly_boundary(self, now: datetime) -> None:
        """Expire homeowner state and invalidate provisional pre-boundary intent."""
        for cancel in tuple(self._pending_single_promotions.values()):
            cancel()
        self._pending_single_promotions.clear()
        for _members, cancel in tuple(self._pending_overlapping_group_promotions.values()):
            cancel()
        self._pending_overlapping_group_promotions.clear()
        self._pending_external_leaves.clear()
        self._external_correlator.reset()
        self._external_burst = None
        self._external_group_burst_topology = {}
        self._external_group_last_observed_at = None
        self._scene_displacement_until.clear()
        self._scene_displacement_evidence.clear()
        self._recent_surface_appearance_evidence.clear()
        super()._handle_nightly_boundary(now)

    @callback
    def _record_external_topology(
        self, observation: ShadowObservation, new_state: State
    ) -> None:
        """Correlate external topology, then promote only qualified exact intent."""
        if (
            observation.evidence.kind is IntentEvidenceKind.EXPLICIT_HOMEOWNER_COMMAND
            and observation.evidence.attribution_source
            is IntentAttributionSource.HOME_ASSISTANT_USER
        ):
            self._clear_post_boundary_off_for_entity(observation.entity_id)
        if (
            observation.evidence.kind is IntentEvidenceKind.AVAILABILITY_CHANGE
            or observation.evidence.has_parent_id
        ):
            self._off_leaf_evidence.append({
                "timestamp": dt_util.now().isoformat(), "entity_id": observation.entity_id,
                "operation": observation.operation, "sequence": observation.sequence,
                "generation": observation.generation,
                "result": "invalidated_availability_or_parent_context",
            })
            self._pending_external_leaves.pop(observation.entity_id, None)
            self._cancel_pending_single_for_entities((observation.entity_id,))
            self._cancel_pending_group_promotions_for_entities((observation.entity_id,))
        if (
            observation.evidence.attribution_source
            is not IntentAttributionSource.UNATTRIBUTED_EXTERNAL
        ):
            self._trace_armed_off(self._external_burst or {}, {}, observation,
                                  self._member_entity_ids_for_event(observation.entity_id, new_state),
                                  "routing", "excluded_attribution_source")
            super()._record_external_topology(observation, new_state)
            return

        observed_at = dt_util.now()
        members = self._member_entity_ids_for_event(observation.entity_id, new_state)
        if not members:
            self._reset_external_burst_for_cross_surface_leaf(observation.entity_id)
        self._snapshot_group_topology_for_burst(observed_at)
        automatic_reason = (
            self._automatic_external_evidence_reason(observation.entity_id, new_state)
            if not members
            else None
        )
        if automatic_reason is not None:
            self._pending_external_leaves.pop(observation.entity_id, None)
            self._cancel_pending_single_for_entities((observation.entity_id,))
            self._cancel_pending_group_promotions_for_entities((observation.entity_id,))
        elif (
            not members
            and observation.evidence.kind is IntentEvidenceKind.UNKNOWN
            and observation.operation in ("appearance", "off")
            and (observation.operation == "off" or observation.appearance is not None)
        ):
            previous = self._pending_external_leaves.get(observation.entity_id)
            if (
                previous is not None
                and previous.observation.sequence != observation.sequence
                and previous.observation.operation != observation.operation
            ):
                # A materially different newer command supersedes provisional intent.
                # Repeated Hue reports for the same operation (for example slider
                # transition steps) update the retained leaf without restarting the
                # exact-group correlation timer.
                self._cancel_pending_single_for_entities((observation.entity_id,))
                self._cancel_pending_group_promotions_for_entities((observation.entity_id,))
            self._pending_external_leaves[observation.entity_id] = _PendingExternalLeaf(
                observed_at=observed_at,
                observation=observation,
                state=new_state,
            )
        if not members:
            self._off_leaf_evidence.append({
                "timestamp": observed_at.isoformat(), "entity_id": observation.entity_id,
                "operation": observation.operation, "sequence": observation.sequence,
                "generation": observation.generation,
                "result": automatic_reason or (
                    "retained" if observation.entity_id in self._pending_external_leaves
                    else "not_retained_evidence_kind"
                ),
                "evidence_kind": observation.evidence.kind.value,
                "has_parent_id": observation.evidence.has_parent_id,
            })
        self._prune_pending_external_leaves(observed_at)
        self._record_recent_surface_appearance(observation, new_state, members, observed_at)

        super()._record_external_topology(observation, new_state)
        burst = self._external_burst
        if not isinstance(burst, dict):
            self._trace_armed_off({}, {}, observation, members, "routing", "missing_burst")
            return

        candidate = burst.get("external_intent_candidate")
        if not isinstance(candidate, dict):
            self._trace_armed_off(burst, {}, observation, members, "routing", "missing_candidate")
            return
        # Canonical surface OFF semantics outrank a provisional single-leaf
        # candidate. This matters for one-managed-leaf surfaces such as Front Eve.
        # Partial OFFs still fall through because the group gates require the full
        # managed member set.
        if self._promote_armed_group_off(
            burst,
            candidate,
            observation=observation,
            members=members,
            current_entity_id=observation.entity_id,
        ):
            return
        if self._promote_owned_manual_group_off(
            burst,
            candidate,
            observation=observation,
            members=members,
            current_entity_id=observation.entity_id,
        ):
            return
        if candidate.get("qualified") is True:
            self._trace_armed_off(burst, candidate, observation, members,
                                  "routing", "qualified_single_after_group_gates")
            self._promote_single_candidate(
                candidate,
                members,
                current_entity_id=observation.entity_id,
            )
            return
        if self._promote_displaced_surface_appearance(
            burst,
            candidate,
            observation=observation,
            members=members,
            current_entity_id=observation.entity_id,
            new_state=new_state,
        ):
            return
        self._promote_exact_group_candidate(
            burst,
            candidate,
            current_entity_id=observation.entity_id,
            burst_topology=self._external_group_burst_topology,
        )

    @callback
    def _record_recent_surface_appearance(
        self,
        observation: ShadowObservation,
        new_state: State,
        members: tuple[str, ...],
        observed_at: datetime,
    ) -> None:
        """Retain only brief unique appearance evidence for commissioned surfaces."""
        if observation.operation != "appearance":
            return
        for aggregate_id, _guard_id in _SURFACE_GUARDS:
            exact_members = frozenset(
                self._managed_group_members(self._topology_members.get(aggregate_id, ()))
            )
            if len(exact_members) < 2:
                continue
            is_aggregate = observation.entity_id == aggregate_id and bool(members)
            is_leaf = observation.entity_id in exact_members and not members
            if not is_aggregate and not is_leaf:
                continue
            evidence = self._recent_surface_appearance_evidence.get(aggregate_id)
            updated_at = evidence.get("updated_at") if isinstance(evidence, dict) else None
            if (
                not isinstance(updated_at, datetime)
                or (observed_at - updated_at).total_seconds()
                > SCENE_DISPLACEMENT_CORROBORATION_SECONDS
            ):
                evidence = {"leaf_entities": set(), "aggregate_seen": False}
                self._recent_surface_appearance_evidence[aggregate_id] = evidence
            leaf_entities = evidence.get("leaf_entities")
            if not isinstance(leaf_entities, set):
                leaf_entities = set()
                evidence["leaf_entities"] = leaf_entities
            if is_aggregate:
                evidence["aggregate_seen"] = True
            elif (
                observation.appearance is not None
                and self._automatic_external_evidence_reason(observation.entity_id, new_state)
                is None
            ):
                leaf_entities.add(observation.entity_id)
            evidence["updated_at"] = observed_at

    @callback
    def _reset_external_burst_for_cross_surface_leaf(self, entity_id: str) -> None:
        """Do not let unrelated surface churn poison one homeowner correlation window."""
        burst = self._external_burst
        if not isinstance(burst, dict):
            return
        prior_leaves = _string_tuple(burst.get("leaf_entities"))
        if not prior_leaves or entity_id in prior_leaves:
            return

        current_surfaces = self._commissioned_surfaces_for_entity(entity_id)
        if not current_surfaces:
            return
        prior_surfaces = set()
        for prior in prior_leaves:
            prior_surfaces.update(self._commissioned_surfaces_for_entity(prior))
        if not prior_surfaces or current_surfaces & prior_surfaces:
            return

        self._external_correlator.reset()
        self._external_burst = None
        self._external_group_burst_topology = {}
        self._external_group_last_observed_at = None

    @callback
    def _commissioned_surfaces_for_entity(self, entity_id: str) -> set[str]:
        """Return the narrow commissioned ownership surfaces containing one leaf."""
        return {
            aggregate_id
            for aggregate_id, _guard_id in _SURFACE_GUARDS
            if entity_id in self._topology_members.get(aggregate_id, ())
        }

    @callback
    def _automatic_external_evidence_reason(
        self, entity_id: str, new_state: State
    ) -> str | None:
        """Return why context-less leaf telemetry must not be promoted as homeowner intent."""
        now = dt_util.now()
        for aggregate_id, settle_until in tuple(self._scene_recall_settle_until.items()):
            if settle_until < now:
                self._scene_recall_settle_until.pop(aggregate_id, None)
                continue
            if entity_id in self._topology_members.get(aggregate_id, ()):
                return "authoritative Hue scene recall is settling on this surface"

        if (
            entity_id in self.manual_precedence
            and self._nightly_boundary_settling()
        ):
            return "nightly 01:59 boundary settling; ambiguous Hue telemetry defaults to HLM"

        if self._in_post_boundary_off_epoch(entity_id):
            return (
                "post-boundary OFF epoch requires affirmative homeowner provenance; "
                "context-less topology is ambiguous"
            )

        dynamics = new_state.attributes.get("dynamics")
        if (
            new_state.state != "off"
            and isinstance(dynamics, str)
            and dynamics not in ("", "none")
        ):
            return "active Hue dynamics are automatic scene telemetry"

        guard_id = self._active_guard_for_ha_consequence(entity_id)
        if guard_id is not None:
            return f"HA command guard is active for this entity: {guard_id}"
        return None

    @callback
    def _snapshot_group_topology_for_burst(self, observed_at: datetime) -> None:
        """Freeze exact-group authority at burst start so new telemetry cannot self-qualify."""
        previous = self._external_group_last_observed_at
        if previous is None:
            new_burst = True
        else:
            delta = (observed_at - previous).total_seconds()
            new_burst = delta < 0 or delta > EXTERNAL_BURST_WINDOW_SECONDS
        if new_burst:
            self._external_group_burst_topology = dict(self._topology_members)
        self._external_group_last_observed_at = observed_at

    @callback
    def _managed_group_members(self, members: tuple[str, ...] | list[str]) -> tuple[str, ...]:
        """Project raw Hue aggregate membership onto entities HLM actually manages."""
        return tuple(sorted({entity_id for entity_id in members if entity_id in self.entity_ids}))

    @callback
    def _managed_group_topology(
        self, topology: dict[str, tuple[str, ...]]
    ) -> dict[str, tuple[str, ...]]:
        """Project every known Hue aggregate onto HLM-managed members only."""
        return {
            group_id: self._managed_group_members(members)
            for group_id, members in topology.items()
        }

    @callback
    def _surface_group_off_hold_seconds(self, entity_id: str, operation: str) -> float:
        """Return the bounded hold only for Manual-owned or armed canonical surface OFFs."""
        if operation != "off":
            return EXTERNAL_BURST_WINDOW_SECONDS
        armed_groups = self.runtime.engine.group_off_sequences()
        for aggregate_id, _guard_id in _SURFACE_GUARDS:
            managed = self._managed_group_members(
                self._topology_members.get(aggregate_id, ())
            )
            if entity_id not in managed:
                continue
            armed = tuple(sorted(set(armed_groups.get(aggregate_id, ()))))
            if armed and armed == managed:
                return SURFACE_GROUP_OFF_CORRELATION_SECONDS
            if managed:
                layers = tuple(self.runtime.engine.resolve(member).layer for member in managed)
                if all(
                    layer is not None
                    and layer.kind is LayerKind.MANUAL
                    and layer.group_id == aggregate_id
                    for layer in layers
                ):
                    return SURFACE_GROUP_OFF_CORRELATION_SECONDS
        return EXTERNAL_BURST_WINDOW_SECONDS

    @callback
    def _retained_surface_off_members(
        self, members: tuple[str, ...]
    ) -> tuple[_PendingExternalLeaf, ...] | None:
        """Return one coherent exact managed OFF set independent of ordinary burst rollover."""
        pending = tuple(self._pending_external_leaves.get(entity_id) for entity_id in members)
        if any(item is None for item in pending):
            return None
        retained = tuple(item for item in pending if item is not None)
        if any(item.observation.operation != "off" for item in retained):
            return None
        generations = {item.observation.generation for item in retained}
        if len(generations) != 1:
            return None
        oldest = min(item.observed_at for item in retained)
        newest = max(item.observed_at for item in retained)
        age = (newest - oldest).total_seconds()
        if age < 0 or age > SURFACE_GROUP_OFF_CORRELATION_SECONDS:
            return None
        return retained

    @callback
    def _promote_single_candidate(
        self,
        candidate: dict[str, object],
        members: tuple[str, ...],
        *,
        current_entity_id: str,
    ) -> None:
        """Promote a leaf immediately unless a pre-known group burst may still resolve."""
        entity_id = candidate.get("entity_id")
        if not isinstance(entity_id, str):
            return

        if (
            current_entity_id in _CONTEXTLESS_SINGLE_MEMBER_SURFACES
            and members == (entity_id,)
        ):
            # A one-member Hue aggregate is propagation of the same physical receipt,
            # not independent evidence that a context-less leaf transition was homeowner
            # intent. The 2026-09-22 Front Eve rebound had exactly this topology.
            self._pending_external_leaves.pop(entity_id, None)
            self._cancel_pending_single_for_entities((entity_id,))
            candidate.update(
                {
                    "promoted_to_homeowner": False,
                    "manual_ownership_recorded": False,
                    "promotion_reason": (
                        "single-member Front Eve aggregate is not independent "
                        "homeowner corroboration"
                    ),
                }
            )
            return

        # A later leaf command needs fresh aggregate corroboration. Reusing the burst start
        # as identity lost rapid ON/OFF or appearance updates within the same window.
        if not members or entity_id not in members:
            return
        pending = self._pending_external_leaves.get(entity_id)
        promotion_key = (pending.observation.sequence if pending else None, entity_id)
        if (
            promotion_key == self._last_external_promotion_key
            and self._last_external_promotion_outcome is not None
        ):
            candidate.update(self._last_external_promotion_outcome)
            return

        if pending is None:
            candidate.update(
                {
                    "promoted_to_homeowner": False,
                    "manual_ownership_recorded": False,
                    "promotion_reason": "qualified burst lacked retained leaf observation",
                }
            )
            return

        # Only a group that was known before this burst can later become exact-group
        # authority. Newly learned aggregate telemetry cannot self-qualify, so it must not
        # delay the already commissioned single-leaf promotion path.
        preknown_members = self._external_group_burst_topology.get(current_entity_id)
        managed_members = self._managed_group_members(members)
        managed_preknown = (
            self._managed_group_members(preknown_members)
            if preknown_members is not None
            else None
        )
        if (
            len(managed_members) > 1
            and managed_preknown is not None
            and frozenset(managed_preknown) == frozenset(managed_members)
        ):
            self._schedule_single_promotion(candidate, promotion_key, pending)
            return

        self._apply_single_promotion(candidate, promotion_key, pending)

    @callback
    def _schedule_single_promotion(
        self,
        candidate: dict[str, object],
        promotion_key: tuple[int | None, str],
        pending: _PendingExternalLeaf,
    ) -> None:
        """Hold a leaf promotion until the current group-correlation window closes."""
        entity_id = pending.observation.entity_id
        existing_key = next(
            (
                key
                for key in self._pending_single_promotions
                if key[1] == entity_id
            ),
            None,
        )
        if existing_key is not None:
            candidate.update(
                {
                    "promoted_to_homeowner": False,
                    "manual_ownership_recorded": False,
                    "promotion_reason": "awaiting exact-group correlation window",
                }
            )
            return

        @callback
        def _finalize(_now: datetime) -> None:
            self._pending_single_promotions.pop(promotion_key, None)
            current = self._pending_external_leaves.get(entity_id)
            if current is None:
                return
            if current.observation.operation != pending.observation.operation:
                return

            latest_candidate = candidate
            burst = self._external_burst
            if isinstance(burst, dict):
                maybe_candidate = burst.get("external_intent_candidate")
                if (
                    isinstance(maybe_candidate, dict)
                    and maybe_candidate.get("qualified") is True
                    and maybe_candidate.get("entity_id") == entity_id
                ):
                    latest_candidate = maybe_candidate

            current_key = (current.observation.sequence, entity_id)
            self._apply_single_promotion(latest_candidate, current_key, current)

        hold_seconds = self._surface_group_off_hold_seconds(
            entity_id, pending.observation.operation
        )
        self._pending_single_promotions[promotion_key] = async_call_later(
            self.hass,
            hold_seconds,
            _finalize,
        )
        candidate.update(
            {
                "promoted_to_homeowner": False,
                "manual_ownership_recorded": False,
                "promotion_reason": "awaiting exact-group correlation window",
            }
        )

    @callback
    def _apply_single_promotion(
        self,
        candidate: dict[str, object],
        promotion_key: tuple[int | None, str],
        pending: _PendingExternalLeaf,
    ) -> None:
        """Apply one retained leaf observation through the existing core path."""
        promoted_observation = ShadowObservation(
            entity_id=pending.observation.entity_id,
            evidence=_correlated_homeowner_evidence(),
            appearance=pending.observation.appearance,
            operation=pending.observation.operation,
            manual_precedence=pending.observation.manual_precedence,
            sequence=pending.observation.sequence,
            generation=pending.observation.generation,
            operation_id=pending.observation.operation_id,
        )
        decision = self.runtime.observe(promoted_observation)
        self._record_evidence(promoted_observation, decision, pending.state)

        outcome = _promotion_outcome(decision)
        candidate.update(outcome)
        self._last_external_promotion_key = promotion_key
        self._last_external_promotion_outcome = outcome

        if decision.mutated:
            self.hass.async_create_task(self.async_save())

    @callback
    def _cancel_pending_single_for_entities(self, entity_ids: tuple[str, ...]) -> None:
        """Cancel provisional leaf promotions consumed by newer or exact-group evidence."""
        wanted = frozenset(entity_ids)
        stale_keys = [
            key for key in self._pending_single_promotions if key[1] in wanted
        ]
        for key in stale_keys:
            cancel = self._pending_single_promotions.pop(key)
            cancel()

    @callback
    def _cancel_pending_group_promotions_for_entities(
        self, entity_ids: tuple[str, ...]
    ) -> None:
        """Cancel deferred exact subgroups consumed or superseded by newer intent."""
        wanted = frozenset(entity_ids)
        stale_keys = [
            key
            for key, (members, _cancel) in self._pending_overlapping_group_promotions.items()
            if members & wanted
        ]
        for key in stale_keys:
            _members, cancel = self._pending_overlapping_group_promotions.pop(key)
            cancel()

    @callback
    def _trace_armed_off(self, burst, candidate, observation, members, stage, result) -> None:
        """Capture gate inputs without refreshing topology, mutating evidence or taking authority."""
        armed = self.runtime.engine.group_off_sequences()
        if not members and observation.entity_id not in armed:
            return
        group = observation.entity_id
        requested = armed.get(group, ())
        source = next((v for v in _SCENE_RECALL_SOURCES.values() if v[0] == group), None)
        def state(entity):
            current = self.hass.states.get(entity) if entity else None
            return current.state if current else None
        pending = {}
        for entity in tuple(sorted(set(requested) | set(members)))[:32]:
            item = self._pending_external_leaves.get(entity)
            pending[entity] = None if item is None else {
                "operation": item.observation.operation,
                "sequence": item.observation.sequence,
                "generation": item.observation.generation,
                "observed_at": item.observed_at.isoformat(),
            }
        self._armed_off_attempts.append({
            "timestamp": dt_util.now().isoformat(), "aggregate_entity": group,
            "operation": observation.operation, "group_id": group,
            "sequence": observation.sequence, "generation": observation.generation,
            "runtime_generation": self.runtime.engine.generation,
            "runtime_revision": self.runtime.engine.revision,
            "stage": stage, "result": result,
            "armed_group_ids": tuple(armed)[:16], "armed_group_count": len(armed),
            "armed_members": requested[:32], "armed_member_count": len(requested),
            "aggregate_members": members[:32], "aggregate_member_count": len(members),
            "burst_leaf_members": tuple(burst.get("leaf_entities", ()))[:32],
            "burst_aggregate_members": tuple(burst.get("aggregate_entities", ()))[:32],
            "burst_started_at": burst.get("started_at"),
            "burst_updated_at": burst.get("updated_at"),
            "burst_topology": burst.get("topology"),
            "snapshot_members": self._external_group_burst_topology.get(group, ())[:32],
            "current_cache_members": self._topology_members.get(group, ())[:32],
            "pending_leaf_ids": tuple(sorted(self._pending_external_leaves))[:32],
            "pending_leaf_count": len(self._pending_external_leaves), "pending_members": pending,
            "pending_single_keys": tuple(self._pending_single_promotions)[:32],
            "guard_state": state(source[1]) if source else "not_configured",
            "sync_state": state(source[2]) if source else "not_configured",
            "canonical_aggregate_state": state(group),
            "candidate_qualified": candidate.get("qualified"),
            "candidate_basis": candidate.get("basis"),
            "candidate_entity": candidate.get("entity_id"),
            "candidate_group": candidate.get("group_id"),
            "attribution_source": observation.evidence.attribution_source.value,
            "has_user_id": observation.evidence.has_user_id,
            "has_parent_id": observation.evidence.has_parent_id,
            "latest_removal_serial": (self.runtime.engine.group_off_changes() or [{}])[-1].get("serial"),
        })

    def off_attempt_diagnostics(self) -> dict:
        return {
            "armed_group_off_attempts": deepcopy(list(self._armed_off_attempts)),
            "off_leaf_evidence": deepcopy(list(self._off_leaf_evidence)),
        }

    @callback
    def _promote_armed_group_off(
        self,
        burst: dict[str, object],
        candidate: dict[str, object],
        *,
        observation: ShadowObservation,
        members: tuple[str, ...],
        current_entity_id: str,
    ) -> bool:
        """Give an already-armed exact group priority over nested Hue aggregates."""
        def reject(reason):
            self._trace_armed_off(burst, candidate, observation, members, "armed", reason)
            return False

        if observation.operation != "off":
            return reject("rejected_not_off")
        if not members:
            return reject("rejected_no_aggregate_members")

        armed = self.runtime.engine.group_off_sequences().get(current_entity_id)
        if armed is None:
            return reject("rejected_group_not_armed")

        exact_members = self._managed_group_members(members)
        armed_members = tuple(sorted(set(armed)))
        if exact_members != armed_members:
            return reject("rejected_aggregate_members_mismatch")

        source = next(
            (
                value
                for value in _SCENE_RECALL_SOURCES.values()
                if value[0] == current_entity_id
            ),
            None,
        )
        if source is not None:
            _, guard_id, sync_entity_id = source
            guard = self.hass.states.get(guard_id)
            if guard is None or guard.state != "off":
                return reject("rejected_guard_not_off")
            if sync_entity_id is not None:
                sync = self.hass.states.get(sync_entity_id)
                if sync is None or sync.state != "off":
                    return reject("rejected_sync_not_off")

            # Commissioned canonical surfaces get the bounded slow-Hue path,
            # while preserving the established gate diagnostics.
            pending = tuple(
                self._pending_external_leaves.get(entity_id) for entity_id in armed_members
            )
            if any(item is None for item in pending):
                return reject("rejected_pending_member_missing")
            retained = tuple(item for item in pending if item is not None)
            if any(item.observation.operation != "off" for item in retained):
                return reject("rejected_pending_operation_not_off")
            surface_generations = {
                item.observation.generation for item in retained
            }
            if len(surface_generations) != 1:
                return reject("rejected_pending_generations_mixed")
            oldest = min(item.observed_at for item in retained)
            newest = max(item.observed_at for item in retained)
            surface_age = (newest - oldest).total_seconds()
            if (
                surface_age < 0
                or surface_age > SURFACE_GROUP_OFF_CORRELATION_SECONDS
            ):
                return reject("rejected_surface_off_evidence_incomplete")
        else:
            # Preserve the generic exact-group contract and its diagnostics.
            leaf_entities = _string_tuple(burst.get("leaf_entities"))
            if leaf_entities != armed_members:
                return reject("rejected_burst_leaves_mismatch")
            pending = tuple(
                self._pending_external_leaves.get(entity_id) for entity_id in armed_members
            )
            if any(item is None for item in pending):
                return reject("rejected_pending_member_missing")
            retained = tuple(item for item in pending if item is not None)
            if any(item.observation.operation != "off" for item in retained):
                return reject("rejected_pending_operation_not_off")

        generations = {item.observation.generation for item in retained}
        if len(generations) != 1:
            return reject("rejected_pending_generations_mixed")
        generation = next(iter(generations))
        if type(generation) is not int:
            return reject("rejected_pending_generation_invalid")

        self._trace_armed_off(burst, candidate, observation, members, "armed", "submitting_to_core")
        sequence = min(int(item.observation.sequence) for item in retained)
        self._cancel_pending_single_for_entities(armed_members)
        self._cancel_pending_group_promotions_for_entities(armed_members)
        for entity_id in armed_members:
            self._pending_external_leaves.pop(entity_id, None)

        candidate.update(
            {
                "qualified": True,
                "entity_id": None,
                "group_id": current_entity_id,
                "basis": "armed_exact_group_second_off",
            }
        )
        result = self.runtime.observe_operation(
            HomeownerOperation(
                operation_id=f"external-armed-group-off:{generation}:{sequence}",
                sequence=sequence,
                generation=generation,
                kind="off",
                evidence=_correlated_homeowner_evidence(),
                members=tuple(
                    MemberOutcome(
                        item.observation.entity_id,
                        manual_precedence=item.observation.manual_precedence,
                    )
                    for item in retained
                ),
                group_id=current_entity_id,
                require_legacy_policy=False,
            )
        )
        candidate.update(_promotion_outcome(result))
        self._trace_armed_off(burst, candidate, observation, members, "core_result", result.reason)

        if result.mutated:
            self._external_correlator.reset()
            self._external_burst = None
            self._external_group_burst_topology = {}
            self._external_group_last_observed_at = None
            self.hass.async_create_task(self.async_save())
        return True

    @callback
    def _promote_owned_manual_group_off(
        self,
        burst: dict[str, object],
        candidate: dict[str, object],
        *,
        observation: ShadowObservation,
        members: tuple[str, ...],
        current_entity_id: str,
    ) -> bool:
        """Release one already-known Manual scene group despite nested Hue aggregate noise."""
        if observation.operation != "off" or not members:
            return False
        if current_entity_id not in {
            value[0] for value in _SCENE_RECALL_SOURCES.values()
        }:
            return False

        source = next(
            (
                value
                for value in _SCENE_RECALL_SOURCES.values()
                if value[0] == current_entity_id
            ),
            None,
        )
        if source is None:
            return False
        _, guard_id, sync_entity_id = source
        guard = self.hass.states.get(guard_id)
        if guard is None or guard.state != "off":
            return False
        if sync_entity_id is not None:
            sync = self.hass.states.get(sync_entity_id)
            if sync is None or sync.state != "off":
                return False

        exact_members = self._managed_group_members(members)

        exposed_layers = tuple(
            self.runtime.engine.resolve(entity_id).layer for entity_id in exact_members
        )
        if any(layer is None for layer in exposed_layers):
            return False
        if any(
            layer.kind.value != "manual"
            or layer.group_id != current_entity_id
            for layer in exposed_layers
            if layer is not None
        ):
            return False

        retained = self._retained_surface_off_members(exact_members)
        if retained is None:
            return False

        sequences = [item.observation.sequence for item in retained]
        generations = {item.observation.generation for item in retained}
        if any(type(sequence) is not int for sequence in sequences) or len(generations) != 1:
            return False
        generation = next(iter(generations))
        if type(generation) is not int:
            return False

        sequence = min(int(item.observation.sequence) for item in retained)
        self._cancel_pending_single_for_entities(exact_members)
        candidate.update(
            {
                "qualified": True,
                "entity_id": None,
                "group_id": current_entity_id,
                "basis": "owned_manual_group_off_with_aggregate_propagation",
            }
        )
        result = self.runtime.observe_operation(
            HomeownerOperation(
                operation_id=f"external-owned-group-off:{generation}:{sequence}",
                sequence=sequence,
                generation=generation,
                kind="off",
                evidence=_correlated_homeowner_evidence(),
                members=tuple(
                    MemberOutcome(
                        item.observation.entity_id,
                        manual_precedence=item.observation.manual_precedence,
                    )
                    for item in retained
                ),
                group_id=current_entity_id,
                require_legacy_policy=False,
            )
        )
        outcome = _promotion_outcome(result)
        candidate.update(outcome)
        if result.mutated:
            self.hass.async_create_task(self.async_save())
        return True

    @callback
    def _promote_displaced_surface_appearance(
        self,
        burst: dict[str, object],
        candidate: dict[str, object],
        *,
        observation: ShadowObservation,
        members: tuple[str, ...],
        current_entity_id: str,
        new_state: State,
    ) -> bool:
        """Promote one corroborated displaced Hue scene without widening normal bursts."""
        if observation.operation != "appearance":
            return False

        now = dt_util.now()
        for aggregate_id, displacement_until in tuple(self._scene_displacement_until.items()):
            if displacement_until < now:
                self._scene_displacement_until.pop(aggregate_id, None)
                self._scene_displacement_evidence.pop(aggregate_id, None)
                continue

            exact_members = self._managed_group_members(
                self._topology_members.get(aggregate_id, ())
            )
            member_set = frozenset(exact_members)
            if len(exact_members) < 2:
                continue
            if current_entity_id != aggregate_id and current_entity_id not in member_set:
                continue

            source = next(
                (
                    value
                    for value in _SCENE_RECALL_SOURCES.values()
                    if value[0] == aggregate_id
                ),
                None,
            )
            if source is None:
                continue
            _surface_id, guard_id, sync_entity_id = source
            guard = self.hass.states.get(guard_id)
            if guard is None or guard.state != "off":
                continue
            if sync_entity_id is not None:
                sync = self.hass.states.get(sync_entity_id)
                if sync is None or sync.state != "off":
                    continue

            evidence = self._scene_displacement_evidence.setdefault(
                aggregate_id,
                {"leaf_entities": set(), "aggregate_seen": False},
            )
            leaf_entities = evidence.get("leaf_entities")
            if not isinstance(leaf_entities, set):
                leaf_entities = set()
                evidence["leaf_entities"] = leaf_entities

            if current_entity_id == aggregate_id and members:
                evidence["aggregate_seen"] = True
            elif (
                current_entity_id in member_set
                and observation.appearance is not None
                and self._automatic_external_evidence_reason(current_entity_id, new_state) is None
            ):
                leaf_entities.add(current_entity_id)

            if evidence.get("aggregate_seen") is not True:
                continue
            if len(leaf_entities) * 4 < len(exact_members) * 3:
                continue

            outcomes: list[MemberOutcome] = []
            for entity_id in exact_members:
                state = self.hass.states.get(entity_id)
                if state is None or state.state in ("unknown", "unavailable"):
                    outcomes.append(
                        MemberOutcome(entity_id, available=False, succeeded=False)
                    )
                    continue
                if state.state != "on":
                    outcomes.append(
                        MemberOutcome(entity_id, available=True, succeeded=False)
                    )
                    continue
                outcomes.append(
                    MemberOutcome(
                        entity_id,
                        appearance=_appearance_from_state(state),
                        manual_precedence=self.manual_precedence.get(entity_id),
                    )
                )

            sequence = self.runtime.reserve_sequence()
            operation_id = (
                f"external-displaced-scene:{self.runtime.engine.generation}:{sequence}"
            )
            result = self.runtime.observe_operation(
                HomeownerOperation(
                    operation_id=operation_id,
                    sequence=sequence,
                    generation=self.runtime.engine.generation,
                    kind="appearance",
                    evidence=_correlated_homeowner_evidence(),
                    members=tuple(outcomes),
                    group_id=aggregate_id,
                    require_legacy_policy=False,
                )
            )
            candidate.update(
                {
                    "qualified": True,
                    "entity_id": None,
                    "group_id": aggregate_id,
                    "basis": "scene_displacement_with_surface_appearance_corroboration",
                    "corroborated_leaf_count": len(leaf_entities),
                    "surface_member_count": len(exact_members),
                    **_promotion_outcome(result),
                }
            )
            self._last_decision = ShadowDecision(
                aggregate_id,
                result.intent,
                result.mutated,
                result.reason,
            )
            if result.mutated:
                for entity_id in exact_members:
                    self._post_boundary_off_entities.discard(entity_id)
                    self._pending_external_leaves.pop(entity_id, None)
                self._cancel_pending_single_for_entities(exact_members)
                self._cancel_pending_group_promotions_for_entities(exact_members)
                self._scene_displacement_until.pop(aggregate_id, None)
                self._scene_displacement_evidence.pop(aggregate_id, None)
                self._external_correlator.reset()
                self._external_burst = None
                self._external_group_burst_topology = {}
                self._external_group_last_observed_at = None
                self.hass.async_create_task(self.async_save())
            return result.mutated

        return False

    @callback
    def _promote_exact_group_candidate(
        self,
        burst: dict[str, object],
        candidate: dict[str, object],
        *,
        current_entity_id: str,
        burst_topology: dict[str, tuple[str, ...]],
    ) -> None:
        """Promote only one pre-known, uniquely identifiable exact aggregate operation."""
        if (
            burst.get("topology")
            != ExternalBurstTopology.MULTI_LEAF_WITH_AGGREGATE_PROPAGATION.value
        ):
            return
        leaf_entities = _string_tuple(burst.get("leaf_entities"))
        aggregate_entities = _string_tuple(burst.get("aggregate_entities"))
        if len(leaf_entities) < 2:
            return

        # Generic exact-group discovery intentionally keeps raw Hue topology.
        # Projecting before discovery can collapse a true exact group and a larger
        # containing group that differs only by unmanaged members. Managed projection
        # is applied later by the commissioned-surface ownership gates.
        group_id = resolve_unique_exact_group(
            leaf_entities=leaf_entities,
            observed_aggregate_entities=aggregate_entities,
            topology_members=burst_topology,
        )

        # An already-armed group owns the next OFF interaction for its exact member
        # set. Nested Hue aggregates from the same physical command must not create a
        # competing group operation that would invalidate that armed sequence before
        # the original aggregate receipt arrives.
        if group_id is not None:
            candidate_members = frozenset(burst_topology.get(group_id, ()))
            leaf_set = frozenset(leaf_entities)
            for armed_group, armed_members in self.runtime.engine.group_off_sequences().items():
                armed_set = frozenset(armed_members)
                if (
                    armed_group != group_id
                    and candidate_members
                    and candidate_members < armed_set
                    and armed_set <= leaf_set
                ):
                    candidate.update(
                        {
                            "promoted_to_homeowner": False,
                            "manual_ownership_recorded": False,
                            "promotion_reason": (
                                "nested group suppressed by armed overlapping group "
                                f"{armed_group}"
                            ),
                        }
                    )
                    return

        # The uniquely exact group must itself be the corroborating event. A
        # containing/nested aggregate arriving later cannot retroactively choose it.
        if group_id is None or group_id != current_entity_id:
            return

        # Once a pre-known exact group is proven, any provisional leaf promotions
        # from this same burst are consumed by the group transaction. They must not
        # race the exact operation or create a newer leaf sequence that rejects it.
        self._cancel_pending_single_for_entities(leaf_entities)

        candidate.update(
            {
                "qualified": True,
                "entity_id": None,
                "group_id": group_id,
                "basis": "unique_exact_group_with_aggregate_propagation",
            }
        )
        pending = [self._pending_external_leaves.get(entity_id) for entity_id in leaf_entities]
        if any(item is None for item in pending):
            candidate.update(
                {
                    "promoted_to_homeowner": False,
                    "manual_ownership_recorded": False,
                    "promotion_reason": "qualified exact group lacked retained member observation",
                }
            )
            return
        retained = tuple(item for item in pending if item is not None)

        kinds = {item.observation.operation for item in retained}
        if len(kinds) != 1 or not kinds <= {"appearance", "off"}:
            candidate.update(
                {
                    "promoted_to_homeowner": False,
                    "manual_ownership_recorded": False,
                    "promotion_reason": "qualified exact group had mixed member operations",
                }
            )
            return
        kind = next(iter(kinds))
        if kind == "appearance" and any(
            item.observation.appearance is None for item in retained
        ):
            candidate.update(
                {
                    "promoted_to_homeowner": False,
                    "manual_ownership_recorded": False,
                    "promotion_reason": "qualified exact group had incomplete member appearance",
                }
            )
            return

        sequences = [item.observation.sequence for item in retained]
        generations = {item.observation.generation for item in retained}
        if any(type(sequence) is not int for sequence in sequences) or len(generations) != 1:
            candidate.update(
                {
                    "promoted_to_homeowner": False,
                    "manual_ownership_recorded": False,
                    "promotion_reason": "qualified exact group lacked coherent ingress identity",
                }
            )
            return
        generation = next(iter(generations))
        if type(generation) is not int:
            return

        oldest = min(item.observed_at for item in retained)
        newest = max(item.observed_at for item in retained)
        age = (newest - oldest).total_seconds()
        if age < 0 or age > EXTERNAL_BURST_WINDOW_SECONDS:
            return

        sequence_pairs = tuple(
            sorted(
                (item.observation.entity_id, int(item.observation.sequence))
                for item in retained
            )
        )
        promotion_key = (group_id, kind, sequence_pairs)
        if (
            promotion_key == self._last_external_group_promotion_key
            and self._last_external_group_promotion_outcome is not None
        ):
            candidate.update(self._last_external_group_promotion_outcome)
            return

        candidate_members = frozenset(leaf_entities)
        armed_superset = next(
            (
                armed_group
                for armed_group, armed_members in self.runtime.engine.group_off_sequences().items()
                if armed_group != group_id
                and candidate_members < frozenset(armed_members)
            ),
            None,
        )
        if kind == "off" and armed_superset is not None:
            self._schedule_overlapping_group_promotion(
                candidate,
                promotion_key,
                group_id,
                retained,
                armed_superset,
            )
            return

        self._apply_exact_group_promotion(candidate, promotion_key, group_id, retained)

    @callback
    def _schedule_overlapping_group_promotion(
        self,
        candidate: dict[str, object],
        promotion_key: tuple[str, str, tuple[tuple[str, int], ...]],
        group_id: str,
        retained: tuple[_PendingExternalLeaf, ...],
        armed_group_id: str,
    ) -> None:
        """Defer a nested OFF while an overlapping armed parent may still complete."""
        if promotion_key in self._pending_overlapping_group_promotions:
            candidate.update(
                {
                    "promoted_to_homeowner": False,
                    "manual_ownership_recorded": False,
                    "promotion_reason": (
                        f"awaiting armed overlapping group {armed_group_id}"
                    ),
                }
            )
            return

        member_ids = frozenset(item.observation.entity_id for item in retained)

        @callback
        def _finalize(_now: datetime) -> None:
            pending = self._pending_overlapping_group_promotions.pop(
                promotion_key, None
            )
            if pending is None:
                return

            armed_members = self.runtime.engine.group_off_sequences().get(
                armed_group_id
            )
            if armed_members is None or not member_ids < frozenset(armed_members):
                return

            for entity_id in member_ids:
                current = self.hass.states.get(entity_id)
                if current is None or current.state != "off":
                    return

            self._apply_exact_group_promotion(
                candidate,
                promotion_key,
                group_id,
                retained,
            )

        cancel = async_call_later(
            self.hass,
            EXTERNAL_BURST_WINDOW_SECONDS,
            _finalize,
        )
        self._pending_overlapping_group_promotions[promotion_key] = (
            member_ids,
            cancel,
        )
        candidate.update(
            {
                "promoted_to_homeowner": False,
                "manual_ownership_recorded": False,
                "promotion_reason": (
                    f"awaiting armed overlapping group {armed_group_id}"
                ),
            }
        )

    @callback
    def _apply_exact_group_promotion(
        self,
        candidate: dict[str, object],
        promotion_key: tuple[str, str, tuple[tuple[str, int], ...]],
        group_id: str,
        retained: tuple[_PendingExternalLeaf, ...],
    ) -> None:
        """Apply a fully correlated exact-group operation through the core."""
        if (
            promotion_key == self._last_external_group_promotion_key
            and self._last_external_group_promotion_outcome is not None
        ):
            candidate.update(self._last_external_group_promotion_outcome)
            return

        generations = {item.observation.generation for item in retained}
        if len(generations) != 1:
            return
        generation = next(iter(generations))
        if type(generation) is not int:
            return

        kind = promotion_key[1]
        sequence = min(int(item.observation.sequence) for item in retained)
        operation = HomeownerOperation(
            operation_id=f"external-group:{generation}:{sequence}",
            sequence=sequence,
            generation=generation,
            kind=kind,
            evidence=_correlated_homeowner_evidence(),
            members=tuple(
                MemberOutcome(
                    item.observation.entity_id,
                    appearance=item.observation.appearance,
                    manual_precedence=item.observation.manual_precedence,
                )
                for item in retained
            ),
            group_id=group_id,
            require_legacy_policy=True,
        )
        result = self.runtime.observe_operation(operation)
        outcome = _promotion_outcome(result)
        candidate.update(outcome)
        self._last_external_group_promotion_key = promotion_key
        self._last_external_group_promotion_outcome = outcome

        if result.mutated:
            self.hass.async_create_task(self.async_save())

    @callback
    def _prune_pending_external_leaves(self, now: datetime) -> None:
        """Bound retained leaf evidence to the same short window as burst correlation."""
        stale = []
        for entity_id, pending in self._pending_external_leaves.items():
            age = (now - pending.observed_at).total_seconds()
            hold_seconds = self._surface_group_off_hold_seconds(
                entity_id, pending.observation.operation
            )
            if age > hold_seconds or age < 0:
                stale.append(entity_id)
        for entity_id in stale:
            item = self._pending_external_leaves[entity_id]
            self._off_leaf_evidence.append({
                "timestamp": now.isoformat(), "entity_id": entity_id,
                "operation": item.observation.operation,
                "sequence": item.observation.sequence,
                "generation": item.observation.generation,
                "result": "pruned_correlation_window",
                "age_seconds": (now - item.observed_at).total_seconds(),
            })
            self._pending_external_leaves.pop(entity_id, None)
            self._cancel_pending_single_for_entities((entity_id,))


def _correlated_homeowner_evidence() -> IntentEvidence:
    return IntentEvidence(
        kind=IntentEvidenceKind.CORRELATED_EXTERNAL_HOMEOWNER_COMMAND,
        succeeded=True,
        attribution_coherent=True,
        attribution_source=IntentAttributionSource.UNATTRIBUTED_EXTERNAL,
        has_user_id=False,
        has_parent_id=False,
    )


def _string_tuple(value: object) -> tuple[str, ...]:
    if not isinstance(value, list) or any(not isinstance(item, str) for item in value):
        return ()
    return tuple(sorted(set(value)))


def _promotion_outcome(decision: ShadowDecision | OperationResult) -> dict[str, object]:
    """Expose intent promotion separately from actual Manual-layer mutation."""
    return {
        "promoted_to_homeowner": (
            decision.intent.disposition is IntentDisposition.HOMEOWNER_INTENT
        ),
        "manual_ownership_recorded": decision.mutated,
        "promotion_reason": decision.reason,
    }
